import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Space Grotesk", "Noto Sans Arabic", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        arabic: ["Noto Sans Arabic", "Space Grotesk", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
      },
      colors: {
        background: {
          primary: "var(--color-bg-primary)",
          surface: "var(--color-bg-surface)",
          elevated: "var(--color-surface-raised)",
          secondary: "var(--color-bg-secondary)",
          tertiary: "var(--color-bg-tertiary)",
          hover: "var(--color-bg-surface-hover)",
          "navy-subtle": "var(--color-bg-navy-subtle)",
          "steel-subtle": "var(--color-bg-steel-subtle)",
        },
        bg: {
          primary: "var(--color-bg-primary)",
          secondary: "var(--color-bg-secondary)",
          tertiary: "var(--color-bg-tertiary)",
          surface: "var(--color-bg-surface)",
        },
        surface: {
          DEFAULT: "var(--color-surface)",
          raised: "var(--color-surface-raised)",
          glass: "var(--color-surface-glass)",
        },
        text: {
          primary: "var(--color-text-primary)",
          secondary: "var(--color-text-secondary)",
          muted: "var(--color-text-muted)",
          disabled: "var(--color-text-disabled)",
        },
        border: {
          DEFAULT: "var(--color-border)",
          strong: "var(--color-border-strong)",
          interactive: "var(--color-border-interactive)",
        },
        "border-default": "var(--color-border)",
        accent: {
          primary: "var(--color-accent-primary)",
          "primary-strong": "var(--color-accent-primary-strong)",
          "primary-hover": "var(--color-accent-primary-hover)",
          success: "var(--color-accent-success)",
          "success-strong": "var(--color-accent-success-strong)",
          tech: "var(--color-accent-tech)",
          "tech-strong": "var(--color-accent-tech-strong)",
          "tech-hover": "var(--color-accent-tech-hover)",
          steel: "var(--color-accent-steel)",
        },
        brand: {
          navy: {
            50: "var(--color-brand-navy-50)",
            100: "var(--color-brand-navy-100)",
            200: "var(--color-brand-navy-200)",
            300: "var(--color-brand-navy-300)",
            400: "var(--color-brand-navy-400)",
            500: "var(--color-brand-navy-500)",
            600: "var(--color-brand-navy-600)",
            700: "var(--color-brand-navy-700)",
            800: "var(--color-brand-navy-800)",
            900: "var(--color-brand-navy-900)",
            950: "var(--color-brand-navy-950)",
          },
          steel: {
            50: "var(--color-brand-steel-50)",
            100: "var(--color-brand-steel-100)",
            200: "var(--color-brand-steel-200)",
            300: "var(--color-brand-steel-300)",
            400: "var(--color-brand-steel-400)",
            500: "var(--color-brand-steel-500)",
            600: "var(--color-brand-steel-600)",
            700: "var(--color-brand-steel-700)",
            800: "var(--color-brand-steel-800)",
            900: "var(--color-brand-steel-900)",
          },
          gold: {
            50: "var(--color-brand-gold-50)",
            100: "var(--color-brand-gold-100)",
            200: "var(--color-brand-gold-200)",
            300: "var(--color-brand-gold-300)",
            400: "var(--color-brand-gold-400)",
            500: "var(--color-brand-gold-500)",
            600: "var(--color-brand-gold-600)",
            700: "var(--color-brand-gold-700)",
            800: "var(--color-brand-gold-800)",
            900: "var(--color-brand-gold-900)",
          },
          softnav: {
            50: "var(--color-brand-softnav-50)",
            100: "var(--color-brand-softnav-100)",
            200: "var(--color-brand-softnav-200)",
            300: "var(--color-brand-softnav-300)",
            400: "var(--color-brand-softnav-400)",
            500: "var(--color-brand-softnav-500)",
            600: "var(--color-brand-softnav-600)",
            700: "var(--color-brand-softnav-700)",
            800: "var(--color-brand-softnav-800)",
            900: "var(--color-brand-softnav-900)",
          },
          sand: {
            50: "var(--color-brand-sand-50)",
            100: "var(--color-brand-sand-100)",
            200: "var(--color-brand-sand-200)",
            300: "var(--color-brand-sand-300)",
            400: "var(--color-brand-sand-400)",
            500: "var(--color-brand-sand-500)",
            600: "var(--color-brand-sand-600)",
            700: "var(--color-brand-sand-700)",
            800: "var(--color-brand-sand-800)",
            900: "var(--color-brand-sand-900)",
          },
          charcoal: {
            50: "var(--color-brand-charcoal-50)",
            100: "var(--color-brand-charcoal-100)",
            200: "var(--color-brand-charcoal-200)",
            300: "var(--color-brand-charcoal-300)",
            400: "var(--color-brand-charcoal-400)",
            500: "var(--color-brand-charcoal-500)",
            600: "var(--color-brand-charcoal-600)",
            700: "var(--color-brand-charcoal-700)",
            800: "var(--color-brand-charcoal-800)",
            900: "var(--color-brand-charcoal-900)",
          },
        },
        ink: "var(--color-ink)",
        success: "var(--color-success)",
        warning: "var(--color-warning)",
        error: "var(--color-error)",
        info: "var(--color-info)",
        grid: "var(--color-grid)",
      },
    },
  },
  plugins: [],
};

export default config;
